[FIXED] `ClassCastException` when trying to open `VoiceCallActivity`
The activity was created with String icon ID, but was trying to extract Int causing following exception.

```
2020-08-10 20:41:11.681 17083-17083/com.example.android.people W/Bundle: Key icon expected Integer but value was a java.lang.String.  The default value 0 was returned.
2020-08-10 20:41:11.682 17083-17083/com.example.android.people W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.os.BaseBundle.getInt(BaseBundle.java:1077)
        at android.content.Intent.getIntExtra(Intent.java:8183)
        at com.example.android.people.VoiceCallActivity.onCreate(VoiceCallActivity.kt:38)
        at android.app.Activity.performCreate(Activity.java:8000)
```

Fix was to pass the Uri that can be used by Glide to show the thumbnail icon.